---
- hosts: center
  become: True
  tasks:
  - name: Print varible
    debug: "You requested user {{ user_to_add }}"
  - name: Creating user {{ user_to_add }}
    user:
      name: "{{ user_to_add }}"
      comment: Managed by ansible
      state: present
  - name: Chek
    shell: |
      grep "{{ user_to_add }}" /etc/passwd
    register: out
  - debug:
      msg: "{{ out.stdout }}"
  - name: Removing user {{ user_to_add  }}
    user:
      name: "{{ user_to_add }}"
      state: absent
