---
- name: Nginx. Install packages
  apt:
    name: "{{ apt_nginx_packages }}"
    state: present

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Templates
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    backup: yes

- name: Remove Index file
  file:
    path: "{{ default_config }}/default"
    state: absent

- name: Copy first page
  copy:
    src: default
    dest: "{{ default_config }}"
  notify:
    - restart nginx

- name: Check content to the sites
  uri:
    url: http://prod.com
    return_content: yes
  register: this
  failed_when: "'Todo' not in this.content"
