---
- name: Include deploy for Debian systems
  include: http_debian.yaml
  when: ansible_os_family == 'Debian'

- name: Include deploy for RedHat systems
  include: http_redhat.yaml
  when: ansible_os_family == 'RedHat'

- name: Remove Index file
  file:
    path: "{{ default_home }}/index.html"
    state: absent


- name: Copy first page
  copy:
    src: index.html
    dest: "{{ default_home }}"
  notify:
    - restart nginx

- meta: flush_handlers

- name: Check file
  shell: |
    cat /etc/os-release | egrep "^NAME" | cut -d'"' -f 2
  register: out
  notify:
    - print out

- meta: flush_handlers
  
- name: Chek connection to Localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 3
  register: out

- debug:
    msg: "{{ out }}"
